# ansible-playbook -i Inventory playbook.yml
---
  - name: Create Zaid Afaneh username 
    hosts: all
    ignore_unreachable: yes
    become: yes 
    remote_user: root
    tasks: 

      - name: Add user        
        user: 
          name: zaidafaneh
          password: $6$t5HY1bOl5CTO$0cYk5plid629x1GicRapsklYVKmhKhvIutQMYJpE0GdXgGRN4lH516VlGpfdo10n4AbK/bboyt0LUMmH9iGBx/ #JOSA123
          groups: 
            # - sudo 
            - root
          comment: Zaid Afaneh's User 
          # generate_ssh_keys: yes
          state: present

      # - name: set expiry time to zero 
      #   caommand: chage -d 0 zaidafaneh
    

      - name: Add Key
        authorized_key: 
          user: zaidafaneh
          key: "{{lookup('file', '/home/zaid/.ssh/id_rsa.pub')}}"

      # - name: "Allow admin users to sudo without a password"
      #   lineinfile:
      #     dest: "/etc/sudoers" # path: in version 2.3
      #     state: "present"
      #     regexp: "^%admin"
      #     line: "%admin ALL=(ALL) NOPASSWD: ALL"


      - name: Add to Sudo Group 
        command: sudo usermod -aG sudo zaidafaneh